name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: run tests and coverage
        run: |
          docker build -t node_hostname_test .
          docker run --rm node_hostname_test /bin/bash -c 'coverage run -m pytest -v && coverage report -m'
